# Generated by Django 3.0.10 on 2021-09-12 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210901_1135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='artistID',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='collectionID',
        ),
        migrations.RemoveField(
            model_name='provenance',
            name='ProvenanceID',
        ),
        migrations.RemoveField(
            model_name='shape',
            name='shapeID',
        ),
    ]
