# Generated by Django 3.2.6 on 2021-09-14 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210912_1024'),
        ('api', '0003_auto_20210914_1834'),
    ]

    operations = [
    ]
